

server:
  port: 8081

springdoc:
  api-docs:
    path : /api-docs

spring:
  datasource:
#    url : jdbc:mysql://localhost:3306/test
#    username : root
#    password : password

    url: jdbc:mysql://db:3306/sales #docker
    username: sales
    password: password
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    #database-platform : org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        format_sql: false
#  /** lazy join */
  jackson:
    serialization:
      fail-on-empty-beans:  false



  mvc:
    converters:
      preferred-json-mapper: gson
      #    management.endpoints.web.base-path =  /actuator
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

    health:
      show-details=always:

  metrics:
    export:
      prometheus:
        enabled: true

#    management.endpoints.web.exposure.include =  health,info,prometheus,metrics
#    management.endpoint.health.show-details =  always
#    management.endpoint.metrics.enabled =  true
#    management.endpoint.prometheus.enabled =  true
#
#
#    spring.servlet.multipart.max-file-size=1000MB   management.endpoints.web.base-path =  /actuator
#    management.endpoints.web.exposure.include =  health,info,prometheus,metrics
#    management.endpoint.health.show-details =  always
#    management.endpoint.metrics.enabled =  true
#    management.endpoint.prometheus.enabled =  true
#
#
#    spring.servlet.multipart.max-file-size=1000MB


jwt:
  secret : saleispower




public_folder :
  absolute  : /Users/nareshswami/Documents/springboot/ADMIN-PANEL-SWAMI-SALES-/src/main/resources/public
  get : src/main/resources/public

profile :
  absolute  : ${public_folder.absolute}/profiles/
  get :  ${public_folder.get}/profiles/

store :
  absolute  : ${public_folder.absolute}/stores/
  get : src/main/resources/public/stores/

item:
  absolute:  ${public_folder.absolute}/items/
  get: ${public_folder.get}/items/


slips :
  absolute : ${public_folder.absolute}/slips/
  get : ${public_folder.get}/slips/
