

server:
  port: 8082



spring:
  datasource:
    url : jdbc:mysql://192.168.1.4:3306/test
    username : sales
    password : password
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    database-platform : org.hibernate.dialect.MySQLDialect
#  /** lazy join */
  jackson:
    serialization:
      fail-on-empty-beans:  false



  mvc:
    converters:
      preferred-json-mapper: gson
      #    management.endpoints.web.base-path =  /actuator
#    management.endpoints.web.exposure.include =  health,info,prometheus,metrics
#    management.endpoint.health.show-details =  always
#    management.endpoint.metrics.enabled =  true
#    management.endpoint.prometheus.enabled =  true
#
#
#    spring.servlet.multipart.max-file-size=1000MB   management.endpoints.web.base-path =  /actuator
#    management.endpoints.web.exposure.include =  health,info,prometheus,metrics
#    management.endpoint.health.show-details =  always
#    management.endpoint.metrics.enabled =  true
#    management.endpoint.prometheus.enabled =  true
#
#
#    spring.servlet.multipart.max-file-size=1000MB